# Generated by Django 3.1.2 on 2020-10-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201014_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(default='', max_length=1000)),
                ('email', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
